
# GITHUB ISSUES REPORT FOR microsoft/vscode-python


Generated on 2023-04-02 using: stale=30, all=0


Only showing items that are new to report in past 1 day(s)


## FOR ISSUES THAT ARE MARKED AS BUGS:


### Issues in vscode-python that have comments from 3rd party after last team response:


\* [10722](https://github.com/microsoft/vscode-python/issues/10722 "Debugging test in VS Code does not work"): 3rd party responded 1 days ago but team last responded 281 days ago

---

## FOR ISSUES THAT ARE NOT MARKED AS BUGS:


### Issues in vscode-python that need a response from team:


\* [20959](https://github.com/microsoft/vscode-python/issues/20959 "Automatically create requirements.txt"): needs an initial team response (1 days old)

\* [20966](https://github.com/microsoft/vscode-python/issues/20966 "EppassData"): needs an initial team response (0 days old)

\* [20967](https://github.com/microsoft/vscode-python/issues/20967 "DLL load failed while importing pyexpat: The specified module could not be found."): needs an initial team response (0 days old)

\* [20968](https://github.com/microsoft/vscode-python/issues/20968 "[Feature requests] Support for metaclass keyword"): needs an initial team response (0 days old)

\* [20969](https://github.com/microsoft/vscode-python/issues/20969 "Extention Unresponsive?"): needs an initial team response (0 days old)

### Issues in vscode-python that have comments from OP after last team response:


\* [19405](https://github.com/microsoft/vscode-python/issues/19405 "Environment created with mamba missing prefix"): OP responded 0 days ago but team last responded 191 days ago

\* [20962](https://github.com/microsoft/vscode-python/issues/20962 "Cannot debug Python tests, got message Invalid message: Found duplicate in &quot;env&quot;: PATH"): OP responded 1 days ago but team last responded 1 days ago

\* [20963](https://github.com/microsoft/vscode-python/issues/20963 "Syntax Highlighting Error"): OP responded 1 days ago but team last responded 1 days ago

### Issues in vscode-python that have comments from 3rd party after last team response:


\* [20828](https://github.com/microsoft/vscode-python/issues/20828 "Invalid message: Found duplicate in &quot;env&quot;: PATH when using virtual environment in Python 3.11"): 3rd party responded 0 days ago but team last responded 2 days ago

\* [20843](https://github.com/microsoft/vscode-python/issues/20843 "ERROR conda.cli.main_run:execute(49)"): 3rd party responded 1 days ago but team last responded 17 days ago

### Issues in vscode-python that have no external responses since team response in 30+ days:


\* [20752](https://github.com/microsoft/vscode-python/issues/20752 "Support discovering interpreters managed using `asdf-vm` which are run from workspace directory"): team response was last response and no others in 30 days
