
# GITHUB ISSUES REPORT FOR microsoft/pylance-release


Generated on 2023-07-14 using: stale=30, all=0


Only showing items that are new to report in past 1 day(s)


## FOR ISSUES THAT ARE MARKED AS BUGS:


### Issues in pylance-release that have no external responses since team response in 30+ days:


\* [4359](https://github.com/microsoft/pylance-release/issues/4359 "PyLance flags new submodules as missing imports with default settings"): team response was last response and no others in 30 days

---

## FOR ISSUES THAT ARE NOT MARKED AS BUGS:


### Issues in pylance-release that need a response from team:


\* [4603](https://github.com/microsoft/pylance-release/issues/4603 "Pylance does not display the function documentation in several cases"): needs an initial team response (1 days old)

\* [4604](https://github.com/microsoft/pylance-release/issues/4604 "Unable to find references of a class instance attribute"): needs an initial team response (0 days old)

### Issues in pylance-release that have comments from OP after last team response:


\* [4502](https://github.com/microsoft/pylance-release/issues/4502 "PYTHONPATH problem"): OP responded 1 days ago but team last responded 2 days ago

\* [4600](https://github.com/microsoft/pylance-release/issues/4600 "deprecated warnings are not displayed when another decorator is under `@deprecated`"): OP responded 1 days ago but team last responded 1 days ago

\* [4601](https://github.com/microsoft/pylance-release/issues/4601 "Go To Symbol doesn't work"): OP responded 1 days ago but team last responded 1 days ago

### Issues in pylance-release that have comments from 3rd party after last team response:


\* [4453](https://github.com/microsoft/pylance-release/issues/4453 "I cannot use autocompletion on some method of libraires."): 3rd party responded 0 days ago but team last responded 38 days ago

\* [4572](https://github.com/microsoft/pylance-release/issues/4572 "Pylance fails to recognize import in Jupyter notebook from transformers package (Symbol is unknown import symbolPylance), but successfully finds import in a pure Python file."): 3rd party responded 1 days ago but team last responded 9 days ago
